### PR TITLE
Fix entity escaping in rss.xml

### PR DESCRIPTION
**Pull request by woefe**
Fixes the entity escaping in the RSS item description. Uses the same escaping mechanism as the [default Hugo rss template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml).

`transform.XMLEscape` requires Hugo 0.121.0 or newer. https://gohugo.io/functions/transform/xmlescape/

### CODE REVIEW

**Comment by woefe** [comment]
What's your policy on the Hugo version? I see the netlify bot is currently building with 0.115.4.

An alternative fix could be to use `| html` as in older versions of the default hugo template: https://github.com/gohugoio/hugo/commit/b4c5df42ff7d2542a661cf06b7a7acb03282bc5a#diff-76032d349eedf06717453a1b01a0ebab2b4324b19533b2825f18eb9a2a377e6b

**Comment by chalin** [comment]
@cjyabraham - just curious, why you're not using the Hugo RSS template?

**Comment by cjyabraham** [comment]
> @cjyabraham - just curious, why you're not using the Hugo RSS template?

@thetwopct, any thoughts?

**Comment by thetwopct** [comment]
> @cjyabraham - just curious, why you're not using the Hugo RSS template?

Tbh, I can't remember now, but pretty sure it wasn't showing the content I wanted it too. I can try switching back if I get time. Also @woefe thanks for your PR, and sorry for not approving it yet, I haven't had a chance to work on this theme recently.

**Review by thetwopct — APPROVED** [review]
Thanks for this, will be released in v0.1.5 of the theme

**Pull request merged**
