### PR TITLE
People profile listing with map

### PR DESCRIPTION
**Pull request by cjyabraham**
[Issue](https://github.com/cncf/dot-org-hugo-theme/issues/56)

[Demo page](https://deploy-preview-58--dot-org-hugo-theme-demo.netlify.app/people-map/)

Note: the exposed Google Maps API key shows on the front-end of the site as well. It is locked down to only a select few referring urls.

### CODE REVIEW

**Comment by cjyabraham** [comment]
@thetwopct I got [the map](https://deploy-preview-58--dot-org-hugo-theme-demo.netlify.app/people-map/) working. I'll leave it for you to style the profile cards and anything else.

**Comment by cjyabraham** [comment]
I went ahead and styled the profile cards, borrowing from CNCF code, so this is now ready for review.

**Comment by thetwopct** [comment]
I'm not overly convinced this is suitable for general inclusion in the theme. Its requirements seem very specific, and other than CNCF I've never seen a map + people layout like this used on a website. So all sites using this theme need to carry this odd component as overhead.

If it’s necessary to include, I would suggest the following:

- Split out the code so its a bit more reusable (if possible within confines of Hugo)
-- add a person component, which would at be useful for users who want to show staff or members (without a map);
-- add a social component for displaying icons
- Add details about how to use the components to the readme 
- Move the googlemaps script in to the theme rather than using unpkg CDN
- I don't love the Google Maps key being in the config example, think it could be confusing, but then using `google_maps_api_key: "{{ env 'GOOGLE_MAPS_API_KEY' }}"` wouldn't be great either.

From a design perspective:
- 4 columns width on desktop looks pretty tight especially with that amount of text per person, 3 columns would look better
- Can the job title / Company / Location be styled a bit better / closer to the name?

Before merging:
- Please rebase on the latest main branch and fix merge conflicts.

Note: I've optimised the images a bit, they seemed very large for simple demo content.

**Comment by cjyabraham** [comment]
Ok, I've [moved this into the devrel theme](https://github.com/DevRel-Foundation/website/commit/e87b88de352b463d153c4f6b9f8805d5b55e8a70) and also incorporated most of your suggestions. I'll close this PR for now then.

**Pull request closed without merging**
