### PR TITLE
Add Pagefind search

### PR DESCRIPTION
**Pull request by cjyabraham**
This addresses #35 by integrating [Pagefind search](https://pagefind.app/).

Preview: https://deploy-preview-37--dot-org-hugo-theme-demo-jh.netlify.app/

It adds the search icon to the topnav on both mobile and desktop. It also demonstrates language-specific search results in both [English](https://deploy-preview-37--dot-org-hugo-theme-demo-jh.netlify.app/search/) and [Spanish](https://deploy-preview-37--dot-org-hugo-theme-demo-jh.netlify.app/es/search/).

You can set up your own local instance of this following [these instructions](https://github.com/cncf/dot-org-hugo-theme/tree/search?tab=readme-ov-file#search-index).

### CODE REVIEW

**Comment by thetwopct** [comment]
@cjyabraham Do you think adding the search to the site/header should be a theme option?

**Comment by thetwopct** [comment]
@cjyabraham A few things popped up when running locally 

1) Was it intentional to leave out [this](https://pagefind.app/docs/indexing/) `data-pagefind-body` attribute as currently the header and footer are searched, which could give some poor results.

```
[Parsing files]
Did not find a data-pagefind-body element on the site.
↳ Indexing all <body> elements on the site.
```

2) There is no /es/demo-page, so maybe Hugo is using the en language content? If Hugo does that, I wonder if we need to add some smarts to the head of the page to detect it (I'm still not 100% sure how the languages/fallover/works)

```
[Reading languages]
* "/es/demo-page/" has no html lang attribute
```

3) I find the Search icon a little bold and jarring. There is a thinner one in the TODO branding icons section which matches the font a little closer. I will swap that in and add a hover color change.

Screenshot-2024-01-22 --15 20 33

4) Locally, I cannot get the search bar to appear on the page, the paths are not valid

Screenshot-2024-01-22 --15 28 10

I've played about with this and cannot get it to load. I also cannot reach the public/pagefind/ file directly (404 error) even though the files exist.

**Comment by cjyabraham** [comment]
1. I did add `data-pagefind-body` [here](https://github.com/cncf/dot-org-hugo-theme/pull/37/files#diff-ec6e7cb6e89cbe10d49085811bd67ad23df375247295fc387da90f5fdc56de7fR8). You may need to build your site first before you run pagefind?

**Comment by cjyabraham** [comment]
> @cjyabraham Do you think adding the search to the site/header should be a theme option?

Yes, good idea.

**Comment by thetwopct** [comment]
- Updated search SVG to be a bit more modern looking
- Moved the search position so flow is better and language is last
- I made the search optional in the UI. 
- Formatted the search in the mobile menu
- Added new npm run script commands for dev and dev build and dev with search (got it working locally eventually)
- Updated the readme 
- Local works, deploy works ✅

**Review by thetwopct — APPROVED** [review]

**Pull request merged**
