### PR TITLE
#34 Adding front-page to theme

### LINKED ISSUE #34: Add an index / home page in the theme
Originally mentioned in #6, another user of the theme has also been confused that there is no easily editable index page, and also that the i18n usage in a template is not explained. We should add one to the theme. This would also improve the demo home page look rather than being a list of pages.

### PR DESCRIPTION
**Pull request by thetwopct**
Objective: To make a front-page using the existing shortcodes and minimal example data

- Adds a placeholder.svg (1kb)
- Allows unsafe HTML in config

Closes #34

### CODE REVIEW

**Review by cjyabraham — APPROVED** [review]
LGTM!

**Comment by cjyabraham** [comment]
Note that #34 also includes explaining i18n usage in the theme. Perhaps that should be split out as a separate issue and addressed elsewhere?

**Comment by thetwopct** [comment]
> Note that #34 also includes explaining i18n usage in the theme. Perhaps that should be split out as a separate issue and addressed elsewhere?

Yeah I saw that and then didn’t really know what it would look like. I’m happy to close unless you think it’s needed.

**Comment by cjyabraham** [comment]
> > Note that #34 also includes explaining i18n usage in the theme. Perhaps that should be split out as a separate issue and addressed elsewhere?
> 
> Yeah I saw that and then didn’t really know what it would look like. I’m happy to close unless you think it’s needed.

Sure, fine to skip for now. I don't think I had a problem figuring the i18n out...

**Pull request merged**
