### PR TITLE
fixes escaping of img tag in nested shortcodes (#51)

### PR DESCRIPTION
**Pull request by cjyabraham**

### CODE REVIEW

**Comment by thetwopct** [comment]
So the problem was the indentation only? Or am I missing something.

**Comment by cjyabraham** [comment]
Yes, the indentation was the problem. It was causing it to enclose the `` tag in `<pre><code>` tags for some reason.

**Comment by thetwopct** [comment]
Wow. 😂 well I guess that reiterates the conclusion from yesterday's broken urls issue.

**Comment by cjyabraham** [comment]
Ya, it's especially weird that it would only escape the img tag when enclosed in another shortcode. It worked fine when not enclosed. 

Yes, Hugo does seem to have a lot of these pesky idiosyncrasies which can unexpectedly stymie a project.

**Review by thetwopct — APPROVED** [review]

**Pull request merged**
